INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('beat-tape-1', 'Beat Tape #1', 'price_1U6t7RLpcL2yfpNfeyU3XDlH', 'ep', 599, 'albums/beat-tape-1/beat-tape-1-mp3-320.zip', 'albums/beat-tape-1/beat-tape-1-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('beat-tape-2', 'Beat Tape #2', 'price_1U6t7TLpcL2yfpNfkBJlqSQB', 'ep', 599, 'albums/beat-tape-2/beat-tape-2-mp3-320.zip', 'albums/beat-tape-2/beat-tape-2-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('black-is-beautiful', 'Black is Beautiful', 'price_1U6t7VLpcL2yfpNfR5GWQsoY', 'ep', 599, 'albums/black-is-beautiful/black-is-beautiful-mp3-320.zip', 'albums/black-is-beautiful/black-is-beautiful-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('bojjis-resolve-2', 'Bojji''s Resolve', 'price_1U6t7ZLpcL2yfpNfkEMXBko5', 'album', 999, 'albums/bojjis-resolve-2/bojjis-resolve-2-mp3-320.zip', 'albums/bojjis-resolve-2/bojjis-resolve-2-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('it-is-what-it-is', 'It is what it is', 'price_1U6t7bLpcL2yfpNfTZk7vUtj', 'album', 999, 'albums/it-is-what-it-is/it-is-what-it-is-mp3-320.zip', 'albums/it-is-what-it-is/it-is-what-it-is-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('jeremiah-29-11', 'Jeremiah 29:11', 'price_1U6t7cLpcL2yfpNf6JPQb6Me', 'ep', 599, 'albums/jeremiah-29-11/jeremiah-29-11-mp3-320.zip', 'albums/jeremiah-29-11/jeremiah-29-11-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('new-start', 'New Start', 'price_1U6t7dLpcL2yfpNfqPfPobEg', 'album', 999, 'albums/new-start/new-start-mp3-320.zip', 'albums/new-start/new-start-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('perspective', 'Perspective', 'price_1U6t7fLpcL2yfpNfgOd5wEkP', 'ep', 599, 'albums/perspective/perspective-mp3-320.zip', 'albums/perspective/perspective-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('perspective-2', 'Perspective', 'price_1U6t7gLpcL2yfpNfaMwiZnzs', 'album', 999, 'albums/perspective-2/perspective-2-mp3-320.zip', 'albums/perspective-2/perspective-2-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('perspectives-pt-1', 'Perspectives pt.1', 'price_1U6t7iLpcL2yfpNfj7gou2GY', 'album', 999, 'albums/perspectives-pt-1/perspectives-pt-1-mp3-320.zip', 'albums/perspectives-pt-1/perspectives-pt-1-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('ryok', 'Ryokō', 'price_1U6t7kLpcL2yfpNfFOhJXDgd', 'album', 999, 'albums/ryok/ryok-mp3-320.zip', 'albums/ryok/ryok-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('shoot-the-j', 'Shoot The J', 'price_1U6t7nLpcL2yfpNf7o1VkJT2', 'album', 999, 'albums/shoot-the-j/shoot-the-j-mp3-320.zip', 'albums/shoot-the-j/shoot-the-j-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('sorbet', 'Sorbet', 'price_1U6t7pLpcL2yfpNf8o0pJxl9', 'ep', 599, 'albums/sorbet/sorbet-mp3-320.zip', 'albums/sorbet/sorbet-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('sp-ep-the-next-chapter', 'SP EP: The Next Chapter', 'price_1U6t7qLpcL2yfpNf2tqNTGL8', 'ep', 599, 'albums/sp-ep-the-next-chapter/sp-ep-the-next-chapter-mp3-320.zip', 'albums/sp-ep-the-next-chapter/sp-ep-the-next-chapter-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('space-2-be', 'Space 2 Be', 'price_1U6t7rLpcL2yfpNfKpwLoz0K', 'album', 999, 'albums/space-2-be/space-2-be-mp3-320.zip', 'albums/space-2-be/space-2-be-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('the-journey', 'The Journey', 'price_1U6t7tLpcL2yfpNfD5Jr9YoM', 'album', 999, 'albums/the-journey/the-journey-mp3-320.zip', 'albums/the-journey/the-journey-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('ball-so-hard', 'Ball So Hard', 'price_1U6t7uLpcL2yfpNf9rbEb63L', 'single', 299, 'albums/ball-so-hard/ball-so-hard-mp3-320.zip', 'albums/ball-so-hard/ball-so-hard-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('bando-matthew-jamison-edit', 'Bando (Matthew Jamison Edit)', 'price_1U6t7wLpcL2yfpNfdkH0yOpg', 'single', 299, 'albums/bando-matthew-jamison-edit/bando-matthew-jamison-edit-mp3-320.zip', 'albums/bando-matthew-jamison-edit/bando-matthew-jamison-edit-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('black-vegas', 'Black Vegas', 'price_1U6t7yLpcL2yfpNfXLhjCkmr', 'single', 299, 'albums/black-vegas/black-vegas-mp3-320.zip', 'albums/black-vegas/black-vegas-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('dangerous-by-busta-rhymes-matthew-jamison-edit', 'Dangerous by Busta Rhymes (Matthew Jamison Edit)', 'price_1U6t81LpcL2yfpNfaVq8qogi', 'single', 299, 'albums/dangerous-by-busta-rhymes-matthew-jamison-edit/dangerous-by-busta-rhymes-matthew-jamison-edit-mp3-320.zip', 'albums/dangerous-by-busta-rhymes-matthew-jamison-edit/dangerous-by-busta-rhymes-matthew-jamison-edit-wav.zip', 0);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('grace-alone', 'Grace alone', 'price_1U6t83LpcL2yfpNfw7ADXHLA', 'single', 299, 'albums/grace-alone/grace-alone-mp3-320.zip', 'albums/grace-alone/grace-alone-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('hallelujah', 'Hallelujah', 'price_1U6t84LpcL2yfpNf6P8vpJY2', 'single', 299, 'albums/hallelujah/hallelujah-mp3-320.zip', 'albums/hallelujah/hallelujah-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('hold-on-be-strong-matthew-jamison-edit', 'Hold On Be Strong (Matthew Jamison Edit)', 'price_1U6t86LpcL2yfpNfiDPJ03Re', 'single', 299, 'albums/hold-on-be-strong-matthew-jamison-edit/hold-on-be-strong-matthew-jamison-edit-mp3-320.zip', 'albums/hold-on-be-strong-matthew-jamison-edit/hold-on-be-strong-matthew-jamison-edit-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('love-bounce', 'Love Bounce', 'price_1U6t87LpcL2yfpNfNj9PfSSa', 'single', 299, 'albums/love-bounce/love-bounce-mp3-320.zip', 'albums/love-bounce/love-bounce-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('noh-talent', '(Noh)_Talent', 'price_1U6t89LpcL2yfpNfmxN5H1at', 'single', 299, 'albums/noh-talent/noh-talent-mp3-320.zip', 'albums/noh-talent/noh-talent-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('sideshow', 'Sideshow', 'price_1U6t8ALpcL2yfpNfyx0CSAsm', 'single', 299, 'albums/sideshow/sideshow-mp3-320.zip', 'albums/sideshow/sideshow-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('the-blessing', 'The Blessing', 'price_1U6t8DLpcL2yfpNft7e57uMd', 'single', 299, 'albums/the-blessing/the-blessing-mp3-320.zip', 'albums/the-blessing/the-blessing-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('twice-matthew-jamison-edit', 'Twice [Matthew Jamison Edit]', 'price_1U6t8GLpcL2yfpNfS2LwBdJz', 'single', 299, 'albums/twice-matthew-jamison-edit/twice-matthew-jamison-edit-mp3-320.zip', 'albums/twice-matthew-jamison-edit/twice-matthew-jamison-edit-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('we-got-the-keys', 'We got the keys', 'price_1U6t8HLpcL2yfpNfh3j46x1e', 'single', 299, 'albums/we-got-the-keys/we-got-the-keys-mp3-320.zip', 'albums/we-got-the-keys/we-got-the-keys-wav.zip', 1);
INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('wedobeatschallenge-9', 'Wedobeatschallenge #9', 'price_1U6t8JLpcL2yfpNfaJ4KvZja', 'single', 299, 'albums/wedobeatschallenge-9/wedobeatschallenge-9-mp3-320.zip', 'albums/wedobeatschallenge-9/wedobeatschallenge-9-wav.zip', 1);
-- Bass sample packs. Commented until the LIVE Stripe prices exist -- pasting a
-- placeholder id here would let a checkout reach Stripe and fail on the buyer.
-- Uncomment with the real price_... ids, then run this file.
--
-- INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('infinity-loops', 'INFINITY LOOPS', 'price_LIVE_TODO', 'pack', 2000, 'albums/infinity-loops/infinity-loops-wav.zip', 'albums/infinity-loops/infinity-loops-wav.zip', 1);
-- INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('bass-latin-vol-1', 'BASS SAMPLE PACK VOL. 1 [LATIN EDITION]', 'price_LIVE_TODO', 'pack', 2000, 'albums/bass-latin-vol-1/bass-latin-vol-1-wav.zip', 'albums/bass-latin-vol-1/bass-latin-vol-1-wav.zip', 1);
-- The bundle owns no file: its two key slots are the two pack zips above.
-- INSERT OR REPLACE INTO albums (slug, title, stripe_price_id, kind, price_cents, r2_key_mp3, r2_key_wav, active) VALUES ('bass-samples-bundle', 'BASS SAMPLE PACKS BUNDLE', 'price_LIVE_TODO', 'bundle', 3500, 'albums/bass-latin-vol-1/bass-latin-vol-1-wav.zip', 'albums/infinity-loops/infinity-loops-wav.zip', 1);
